export const UPDATE_SESSION_TIME = 'UPDATE_SESSION_TIME';
export const UPDATE_BREAK_TIME = 'UPDATE_BREAK_TIME';

export const START_POMODORO = 'START_POMODORO';
export const STOP_POMODORO = 'STOP_POMODORO';
export const CLEAR_POMODORO = 'CLEAR_POMODORO';

export const COUNTER_NOT_STARTED = 'COUNTER_NOT_STARTED';
export const COUNTER_STARTED = 'COUNTER_STARTED';
export const COUNTER_PAUSED = 'COUNTER_PAUSED';
export const COUNTER_CLEARED = 'COUNTER_CLEARED';

export const SESSION_IN_PROGRESS = 'SESSION_IN_PROGRESS';
export const BREAK_IN_PROGRESS = 'BREAK_IN_PROGRESS';

export const SWITCH_POMODORO_STATE = 'SWITCH_POMODORO_STATE';

export const UPDATE_REMAINING_SECONDS = 'UPDATE_REMAINING_SECONDS';
